export const jobs = [
  {
    id: 1,
    title: "Software Engineer",
    company: "TechCorp",
    bannerUrl: "/banner-placeholder.jfif",
    profileUrl: "/profile-placeholder.jfif",
    location: "San Francisco, CA",
    type: "Full-time",
    description:
      "Join our team to build innovative web applications using the latest technologies. We're looking for a Software Engineer with experience in JavaScript, React, and Node.js.",
    companyRating: 4.2,
    workHours: "9:00 AM - 5:00 PM, Mon-Fri",
    workMode: "On-site with remote options",
    requiredSkills: ["JavaScript", "React", "Node.js"],
    fullDescription:
      "As a Software Engineer at TechCorp, you'll design and develop web applications, work closely with other developers, and bring projects to completion using agile methodologies.",
    responsibilities: [
      "Develop and maintain web applications",
      "Collaborate with cross-functional teams",
      "Participate in code reviews",
      "Identify and fix bugs",
    ],
    qualifications: [
      "3+ years experience in JavaScript and React",
      "Familiarity with Node.js",
      "Strong problem-solving skills",
    ],
    salaryRange: "80,000 - 120,000 USD per year",
    benefits: ["Health insurance", "401(k) matching", "Paid time off"],
    postedDate: "2024-10-09",
    expiryDate: "2024-12-09",
    experienceLevel: "Mid-level",
    industry: "Technology",
    educationRequirements: [
      "Bachelor's degree in Computer Science or related field",
    ],
    applicationUrl: "https://company.com/careers/apply",
    contactEmail: "hr@techcorp.com",
    internalId: "TC-SWE-001",
    viewsCount: 238,
    applicantsCount: 12,
  },
  {
    id: 2,
    title: "توسعه‌دهنده نرم‌افزار",
    company: "شرکت فناوری نوآور",
    bannerUrl: "",
    profileUrl: "",
    location: "مشهد، ایران",
    type: "تمام‌ وقت",
    description:
      "به دنبال یک توسعه‌دهنده نرم‌افزار با تجربه برای ایجاد و پیاده‌سازی سیستم‌های کارآمد و پایدار هستیم.",
    companyRating: 4.6,
    workHours: "8:30 صبح تا 4:30 عصر، شنبه تا چهارشنبه",
    workMode: "حضوری",
    requiredSkills: ["جاوا", "پایتون", "MongoDB"],
    fullDescription:
      "در این نقش، شما مسئول طراحی و پیاده‌سازی سیستم‌های نرم‌افزاری خواهید بود که توسط تیم توسعه و نگهداری می‌شوند. دانش عمیق در جاوا و پایتون مورد نیاز است.",
    responsibilities: [
      "توسعه و بهینه‌سازی سیستم‌ها",
      "طراحی پایگاه داده",
      "بررسی و حل مشکلات کد",
    ],
    qualifications: [
      "تجربه در جاوا و پایتون",
      "تسلط به پایگاه داده MongoDB",
      "مهارت‌های عالی در حل مسائل",
    ],
    salaryRange: "60,000 - 100,000 USD per year",
    benefits: ["بیمه سلامت", "پاداش عملکرد", "زمان مرخصی با حقوق"],
    postedDate: "2024-11-08",
    expiryDate: "2024-12-09",
    experienceLevel: "Mid-level",
    industry: "Technology",
    educationRequirements: ["مدرک کارشناسی در رشته نرم‌افزار یا رشته مرتبط"],
    applicationUrl: "https://novaco.ir/careers/apply",
    contactEmail: "hr@novaco.ir",
    internalId: "NC-DEV-002",
    viewsCount: 102,
    applicantsCount: 5,
  },
  {
    id: 3,
    title: "مدیر پروژه",
    company: "گروه ساختمانی ایران سازه",
    bannerUrl: "",
    profileUrl: "",
    location: "تهران، ایران",
    type: "پروژه‌ای",
    description:
      "نیازمند یک مدیر پروژه با تجربه برای مدیریت پروژه‌های ساختمانی و تضمین کیفیت و زمان‌بندی مناسب هستیم.",
    companyRating: 4.4,
    workHours: "شناور",
    workMode: "حضوری",
    requiredSkills: [
      "مدیریت پروژه",
      "مهارت‌های ارتباطی",
      "آشنایی با نرم‌افزارهای مدیریت",
    ],
    fullDescription:
      "به عنوان مدیر پروژه، شما بر روند اجرایی پروژه‌های ساختمانی نظارت خواهید داشت، تیم‌ها را هماهنگ کرده و اطمینان از زمان‌بندی و کیفیت خواهید داشت.",
    responsibilities: [
      "برنامه‌ریزی و نظارت بر پروژه‌ها",
      "مدیریت منابع انسانی",
      "گزارش‌دهی منظم به مدیریت",
    ],
    qualifications: [
      "5 سال تجربه در مدیریت پروژه",
      "آشنایی با نرم‌افزارهای Primavera و MS Project",
      "مهارت‌های عالی در مدیریت و هدایت تیم‌ها",
    ],
    salaryRange: "100,000 - 150,000 USD per project",
    benefits: ["پاداش پروژه", "بیمه سلامت"],
    postedDate: "2024-11-09",
    expiryDate: "2024-12-31",
    experienceLevel: "Senior",
    industry: "Construction",
    educationRequirements: ["مدرک کارشناسی در رشته مهندسی عمران یا رشته مرتبط"],
    applicationUrl: "https://iransazeh.com/careers/apply",
    contactEmail: "hr@iransazeh.com",
    internalId: "IS-PM-003",
    viewsCount: 184,
    applicantsCount: 8,
  },
];
