import {
  JobPosting,
  JobType,
  WorkMode,
  CompensationModel,
  JobCategory,
  JobIndustry,
  ExperienceLevel,
} from "./types";

export const jobPostings: JobPosting[] = [
  {
    jobDetails: {
      id: 101,
      title: "Front-End Developer",
      description:
        "We are looking for a skilled Front-End Developer to join our team and work on web applications.",
      shortDescription:
        "Develop front-end applications with a focus on user experience.",
      jobType: [JobType.FullTime, JobType.PartTime],
      jobCategory: JobCategory.SoftwareDevelopment,
      jobIndustry: JobIndustry.InformationTechnology,
      requiredGender: "any",
      preferredGender: "any",
      skills: [
        { name: "JavaScript", isRequired: true },
        { name: "React", isRequired: true },
        { name: "CSS", isRequired: true },
        { name: "TypeScript", isRequired: false, isPreferred: true },
      ],
      experience: [
        { level: ExperienceLevel.Entry, isRequired: true },
        { level: ExperienceLevel.Junior, isRequired: false, isPreferred: true },
      ],
      qualifications: [
        "Bachelor's degree in Computer Science or related field",
      ],
      educationRequirements: ["Bachelor's degree"],
      responsibilities: [
        "Develop responsive web applications",
        "Collaborate with UI/UX designers",
        "Optimize applications for speed and scalability",
      ],
      compensationModel: CompensationModel.Salary,
      workMode: [WorkMode.Remote],
      workHours: "40 hours/week",
      benefits: ["Health insurance", "Remote work stipend", "Paid time off"],
      salaryRange: { min: 70000, max: 90000, currency: "USD" },
      location: { city: "San Francisco", country: "USA" },
      applicationDeadline: new Date("2024-12-31"),
      postedDate: new Date("2024-10-01"),
      hiringUrgency: "standard",
      preferredCommunicationChannels: ["email", "videoCall"],
      visaSponsorship: true,
      relocationSupport: { provided: false },
      equalOpportunityEmployer: true,
    },
    applicationTracking: [
      {
        applicantId: 1,
        status: "Interviewed",
        feedback: "Strong technical skills; awaiting final decision",
        lastUpdated: new Date("2024-10-15"),
      },
      {
        applicantId: 2,
        status: "Pending",
        feedback: "",
        lastUpdated: new Date("2024-10-12"),
      },
    ],
  },
  {
    jobDetails: {
      id: 102,
      title: "Data Scientist",
      description:
        "Join our data science team to work on predictive analytics and machine learning models.",
      shortDescription: "Analyze data and develop machine learning models.",
      jobType: [JobType.Contract, JobType.Freelance],
      jobCategory: JobCategory.DataScienceAndAnalytics,
      jobIndustry: JobIndustry.Finance,
      requiredGender: "any",
      preferredGender: "any",
      skills: [
        { name: "Python", isRequired: true },
        { name: "Machine Learning", isRequired: true },
        { name: "SQL", isRequired: true },
        { name: "Data Analysis", isRequired: true },
        { name: "TensorFlow", isRequired: false, isPreferred: true },
      ],
      experience: [
        { level: ExperienceLevel.Mid, isRequired: true },
        { level: ExperienceLevel.Senior, isRequired: false, isPreferred: true },
      ],
      qualifications: ["Master's degree in Data Science or related field"],
      educationRequirements: ["Master's degree"],
      responsibilities: [
        "Develop predictive models",
        "Collaborate with data engineers",
        "Perform data visualization and reporting",
      ],
      compensationModel: CompensationModel.Hourly,
      workMode: [WorkMode.Remote],
      workHours: "Flexible",
      benefits: ["Remote work stipend", "Professional development budget"],
      salaryRange: { min: 50, max: 70, currency: "USD" },
      location: { city: "Remote", country: "Worldwide" },
      applicationDeadline: new Date("2025-01-15"),
      postedDate: new Date("2024-11-05"),
      hiringUrgency: "urgent",
      preferredCommunicationChannels: ["email", "messagingApp"],
      visaSponsorship: false,
      relocationSupport: { provided: false },
      equalOpportunityEmployer: true,
      diversityAndInclusionStatement:
        "We embrace diversity and encourage applicants from all backgrounds.",
    },
    applicationTracking: [
      {
        applicantId: 3,
        status: "Reviewed",
        feedback: "Good experience with ML; proceeding to interview",
        lastUpdated: new Date("2024-11-10"),
      },
    ],
  },
  {
    jobDetails: {
      id: 103,
      title: "Marketing Specialist",
      description:
        "Seeking a Marketing Specialist to drive brand awareness and customer engagement.",
      shortDescription: "Develop marketing strategies and manage campaigns.",
      jobType: [JobType.PartTime, JobType.ProjectBased],
      jobCategory: JobCategory.Marketing,
      jobIndustry: JobIndustry.ConsumerGoods,
      requiredGender: "any",
      preferredGender: "any",
      skills: [
        { name: "Digital Marketing", isRequired: true },
        { name: "SEO", isRequired: true },
        { name: "Content Creation", isRequired: false, isPreferred: true },
        { name: "Social Media Management", isRequired: true },
      ],
      experience: [{ level: ExperienceLevel.Junior, isRequired: true }],
      qualifications: ["Bachelor's degree in Marketing or related field"],
      educationRequirements: ["Bachelor's degree"],
      responsibilities: [
        "Plan and execute digital marketing campaigns",
        "Optimize content for search engines",
        "Monitor and report on campaign performance",
      ],
      compensationModel: CompensationModel.Commission,
      workMode: [WorkMode.Onsite],
      workHours: "20 hours/week",
      benefits: ["Flexible schedule", "Employee discount"],
      salaryRange: { min: 40000, max: 50000, currency: "USD" },
      location: { city: "New York", country: "USA" },
      applicationDeadline: new Date("2024-12-10"),
      postedDate: new Date("2024-11-01"),
      hiringUrgency: "immediate",
      preferredCommunicationChannels: ["phone", "email"],
      visaSponsorship: false,
      relocationSupport: {
        provided: true,
        description: "Assistance with relocation expenses up to $2,000",
      },
      equalOpportunityEmployer: true,
      analytics: {
        usageData: {
          applicationRates: 15,
          jobPostViews: 320,
          pageViews: 2111,
        },
        performanceMetrics: {
          responseTimes: [21],
          successRates: 10,
        },
      },
    },
    applicationTracking: [
      {
        applicantId: 1,
        status: "Pending",
        feedback: "",
        lastUpdated: new Date("2024-11-10"),
      },
    ],
  },
];
